parameters:
#    application_page.example.class: Application\PageBundle\Example

services:
#    application_page.example:
#        class: %application_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
