pm_list:
    pattern:  /pm
    defaults: { _controller: EuroPrivateMessageBundle:PrivateMessage:list, archives: false }

pm_list_archives:
    pattern:  /pm/archives
    defaults: { _controller: EuroPrivateMessageBundle:PrivateMessage:list, archives: true }

pm_read:
    pattern: /pm/read/{id}/{title}
    defaults: { _controller: EuroPrivateMessageBundle:PrivateMessage:read }
    requirements:
        id: "\d+"
