pm_index:
    pattern:  /pm
    defaults: { _controller: EuroPrivateMessageBundle:PrivateMessage:index }

pm_new:
    pattern:  /pm/new
    defaults: { _controller: EuroPrivateMessageBundle:PrivateMessage:new, to: 0 }

pm_new_to:
    pattern:  /pm/{to}/new
    defaults: { _controller: EuroPrivateMessageBundle:PrivateMessage:new }

pm_read:
    pattern:  /pm/{id}/read
    defaults: { _controller: EuroPrivateMessageBundle:PrivateMessage:read }
