pm_list:
    pattern:  /pm
    defaults: { _controller: EuroPrivateMessageBundle:PrivateMessage:list, archives: false }

pm_list_archives:
    pattern:  /pm/archives
    defaults: { _controller: EuroPrivateMessageBundle:PrivateMessage:list, archives: true }
