parameters:
#    euro_private_message.example.class: Euro\PrivateMessageBundle\Example

services:
#    euro_private_message.example:
#        class: %euro_private_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
