services:
    twig.extension.euro_pm:
        class: Euro\PrivateMessageBundle\Twig\Extension\TwigExtension
        arguments:
            doctrine: "@doctrine"
        tags:
            - { name: twig.extension }
