EuroCoinBundle_homepage:
    pattern:  /
    defaults: { _controller: EuroCoinBundle:Default:index }

EuroCoinBundle_country:
    resource: "@EuroCoinBundle/Resources/config/routing/country.yml"
    prefix:   /country

EuroCoinBundle_coin:
    resource: "@EuroCoinBundle/Resources/config/routing/coin.yml"
    prefix:   /coin
