coin_add:
    pattern: /coin/{id}/add/{quantity}
    defaults: { _controller: EuroCoinBundle:Coin:addRemove, type: add }
    requirements:
        id: "\d+"
        _method: POST

coin_collection1:
    pattern: /collection/{id}/{country}/{year}
    defaults: { _controller: EuroCoinBundle:Coin:collection, country: null, id: null, type: 1, year: null }
    requirements:
        id: "\d*"

coin_collection2:
    pattern: /collection/commemorative/{id}/{country}/{year}
    defaults: { _controller: EuroCoinBundle:Coin:collection, country: null, id: null, type: 2, year: null }
    requirements:
        id: "\d*"

coin_collection3:
    pattern: /collection/collector/{id}/{country}/{year}
    defaults: { _controller: EuroCoinBundle:Coin:collection, country: null, id: null, type: 3, year: null }
    requirements:
        id: "\d*"

coin_get:
    pattern: /coin/{id}/get
    defaults: { _controller: EuroCoinBundle:Coin:get }
    requirements:
        id: "\d+"
        _method: POST

coin_remove:
    pattern: /coin/{id}/remove/{quantity}
    defaults: { _controller: EuroCoinBundle:Coin:addRemove, type: remove }
    requirements:
        id: "\d+"
        _method: POST

coin_stats:
    pattern: /stats
    defaults: { _controller: EuroCoinBundle:Coin:stats }

countries_list:
    pattern:  /countries
    defaults: { _controller: EuroCoinBundle:Country:list }

exchange_accept:
    pattern: /exchange/{id}/accept
    defaults: { _controller: EuroCoinBundle:Exchange:acceptCancelRefuse, type: 'accept' }
    requirements:
        id: "\d+"

exchange_cancel:
    pattern: /exchange/{id}/cancel
    defaults: { _controller: EuroCoinBundle:Exchange:acceptCancelRefuse, type: 'cancel' }
    requirements:
        id: "\d+"
        
exchange_choose_user:
    pattern: /exchange/new/step-1/users
    defaults: { _controller: EuroCoinBundle:Exchange:chooseUser }

exchange_coins_request:
    pattern: /exchange/new/step-2/coins/request/{id}/{name}
    defaults: { _controller: EuroCoinBundle:Exchange:chooseCoins }
    requirements:
        id: "\d+"

exchange_coins_suggest:
    pattern: /exchange/new/step-3/coins/suggest/{id}/{name}
    defaults: { _controller: EuroCoinBundle:Exchange:proposeCoins }
    requirements:
        id: "\d+"
        _method: POST

exchange_list:
    pattern: /exchanges
    defaults: { _controller: EuroCoinBundle:Exchange:list, all: false }

exchange_list_all:
    pattern: /exchanges/all
    defaults: { _controller: EuroCoinBundle:Exchange:list, all: true }

exchange_refuse:
    pattern: /exchange/{id}/refuse
    defaults: { _controller: EuroCoinBundle:Exchange:acceptCancelRefuse, type: 'refuse' }
    requirements:
        id: "\d+"

exchange_save:
    pattern: /exchange/new/step-4/save/{id}/{name}
    defaults: { _controller: EuroCoinBundle:Exchange:save }
    requirements:
        id: "\d+"
        _method: POST

exchange_show:
    pattern: /exchange/{id}/show
    defaults: { _controller: EuroCoinBundle:Exchange:show }
    requirements:
        id: "\d+"
