coin:
    pattern:  /
    defaults: { _controller: "EuroCoinBundle:Coin:index", country: '', year: '', value: '', commemorative: '' }

coin_get:
    pattern:  /{id}/get
    defaults: { _controller: "EuroCoinBundle:Coin:get" }

coin_show:
    pattern:  /{id}/show
    defaults: { _controller: "EuroCoinBundle:Coin:show" }

coin_filter:
    pattern:  /filter/country-{country}/year-{year}/value-{value}/commemorative-{commemorative}/
    defaults: { _controller: "EuroCoinBundle:Coin:index" }
    requirements:
        country: "\d*"
        year: "(\d{4}[A-Z]*)?"
        value: "\d*"
        commemorative: "(0|1)*"
