coin:
    pattern:  /
    defaults: { _controller: "EuroCoinBundle:Coin:index", country: '', year: '', value: '', commemorative: '', collector: false }

coin_collector:
    pattern:  /collector
    defaults: { _controller: "EuroCoinBundle:Coin:index", country: '', year: '', value: '', commemorative: '', collector: true }

coin_doubles:
    pattern:  /doubles
    defaults: { _controller: "EuroCoinBundle:Coin:doubles" }

coin_doubles_share:
    pattern:  /doubles/{id}
    defaults: { _controller: "EuroCoinBundle:Coin:doublesShare" }
    requirements:
        id: "\d+"

coin_doubles_share_accept:
    pattern:  /doubles/{id}/accept
    defaults: { _controller: "EuroCoinBundle:Coin:doublesShareAccept" }
    requirements:
        id: "\d+"

coin_doubles_share_propose:
    pattern:  /doubles/{from}/propose/{to}
    defaults: { _controller: "EuroCoinBundle:Coin:doublesSharePropose" }
    requirements:
        from: "\d+"
        to: "\d+"

coin_shares:
    pattern:  /shares
    defaults: { _controller: "EuroCoinBundle:Coin:shares" }

coin_show:
    pattern:  /{id}/show
    defaults: { _controller: "EuroCoinBundle:Coin:show" }
    requirements:
        id: "\d+"

coin_filter:
    pattern:  /filter/country-{country}/year-{year}/value-{value}
    defaults: { _controller: "EuroCoinBundle:Coin:index", collector: false }
    requirements:
        country: "\d*"
        year: "\d*"
        value: "\d*"

coin_collector_filter:
    pattern:  /collector/filter/country-{country}/year-{year}/value-{value}
    defaults: { _controller: "EuroCoinBundle:Coin:index", collector: true }
    requirements:
        country: "\d*"
        year: "\d*"
        value: "\d*"

coin_get:
    pattern:  /{id}/get
    defaults: { _controller: "EuroCoinBundle:Coin:get" }
    requirements:
        id: "\d+"
        _method: POST

coin_remove:
    pattern:  /{id}/remove
    defaults: { _controller: "EuroCoinBundle:Coin:remove" }
    requirements:
        id: "\d+"
        _method: POST

coin_add:
    pattern:  /{id}/add
    defaults: { _controller: "EuroCoinBundle:Coin:add" }
    requirements:
        id: "c?\d+"
        _method: POST
