sonata_news:
    title:        'EuroCoin Mania'
    link:         http://www.eurocoin-mania.eu/
    description:  'Manage your Euro coin collection and suggest exchanges to the other users.'
    salt:         'd6103a76bf071c49945ae4d9fd69e98fc'
    permalink_generator: sonata.news.permalink.date # sonata.news.permalink.category

    comment:
        notification:
            emails:   [contact@eurocoin-mania.eu]
            from:     contact@eurocoin-mania.eu
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'
