EuroCoinBundle:
    resource: "@EuroCoinBundle/Resources/config/routing.yml"
    prefix:   /

EuroContactBundle:
    resource: "@EuroContactBundle/Resources/config/routing.yml"
    prefix:  /

EuroPageBundle:
    resource: "@EuroPageBundle/Resources/config/routing.yml"
    prefix:    /

EuroPrivateMessageBundle:
    resource: "@EuroPrivateMessageBundle/Resources/config/routing.yml"
    prefix:   /

ApplicationSonataUserBundle:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing.yml"
    prefix:   /

ApplicationSonataNewsBundle:
    resource: "@ApplicationSonataNewsBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

sonata_page_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

news:
    resource: '@SonataNewsBundle/Resources/config/routing/news.xml'
    prefix: /news

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
