parameters:
#    euro_user.example.class: Euro\UserBundle\Example

services:
#    euro_user.example:
#        class: %euro_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
