<?php

namespace Application\Sonata\NewsBundle\Entity;

use Sonata\NewsBundle\Entity\BaseComment;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Comment extends BaseComment {

	/**
	 * @var integer $id
	 */
	protected $id;

	/**
	 * Get id
	 *
	 * @return integer $id
	 */
	public function getId() {
		return $this->id;
	}

}
