parameters:
#    euro_page.example.class: Euro\PageBundle\Example

services:
#    euro_page.example:
#        class: %application_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
