<?php

namespace Euro\CoinBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoinRepository extends EntityRepository {

	public function findCoinsByCountry(Country $country, $collector) {
		$queryBuidler = $this->createQueryBuilder('c');
		$expr = $queryBuidler->expr();

		return $queryBuidler
						->join('c.value', 'v')
						->join('c.year', 'y')
						->leftJoin('y.workshop', 'w')
						->where($expr->eq('c.country', ':country'))
						->andWhere($expr->eq('c.collector', ':collector'))
						->orderBy('y.year', 'ASC')
						->addOrderBy('w.short_name', 'ASC')
						->addOrderBy('v.value', 'DESC')
						->setParameters(array(
							'collector' => $collector,
							'country' => $country,
						))
						->getQuery()
						->getResult();
	}

}
