<?php

namespace Euro\CoinBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoinRepository extends EntityRepository {

	public function getAllYear() {
		$queryBuiler = $this->createQueryBuilder('c');

		return $queryBuiler
						->select('c.year')
						->distinct()
						->orderBy('c.year', 'ASC')
						->getQuery()
						->getResult();
	}

	public function getCoinsByCountry($country) {
		$queryBuiler = $this->createQueryBuilder('c');
		$expr = $queryBuiler->expr();

		return $queryBuiler
						->join('c.value', 'v')
						->where(
								$expr->eq('c.country', ':country')
						)
						->orderBy('c.year', 'ASC')
						->addOrderBy('v.value', 'DESC')
						->setParameter('country', $country)
						->getQuery()
						->getResult();
	}

}
