<?php

namespace Euro\CoinBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository {

	public function findAll() {
		$queryBuidler = $this->createQueryBuilder('c');

		return $queryBuidler
						->select('c, f')
						->join('c.flag', 'f')
						->orderBy('c.join_date', 'ASC')
						->where('c.join_date < CURRENT_DATE()')
						->getQuery()
						->getResult();
	}

}
