<?php

namespace Euro\CoinBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareRepository extends EntityRepository {

	public function cancelShare($conversation) {
		$queryBuiler = $this->createQueryBuilder('s');
		$expr = $queryBuiler->expr();

		return $queryBuiler->update()
						->set('s.status', Share::STATUS_CANCELED)
						->where($expr->eq('s.pm', ':conversation'))
						->setParameter('conversation', $conversation)
						->getQuery()
						->getResult();
	}

	public function getSharesByUser($user) {
		$queryBuiler = $this->createQueryBuilder('s');
		$expr = $queryBuiler->expr();

		return $queryBuiler
						->join('s.from_user_coin', 'from_uc')
						->join('s.to_user_coin', 'to_uc')
						->where($expr->eq('from_uc.user', ':user'))
						->orWhere($expr->eq('to_uc.user', ':user'))
						->orderBy('s.date', 'DESC')
						->setParameter('user', $user)
						->getQuery()
						->getResult();
	}

	public function setAccepted($id) {
		$queryBuiler = $this->createQueryBuilder('s');
		$expr = $queryBuiler->expr();

		$queryBuiler->update()
				->set('s.status', Share::STATUS_VALIDATED)
				->where($expr->eq('s.id', ':id'))
				->setParameter('id', $id)
				->getQuery()
				->getResult();
	}

}
