<?php

namespace Euro\CoinBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Sonata\UserBundle\Model\UserInterface;

/**
 * ShareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShareRepository extends EntityRepository {

	public function findForUser(UserInterface $user, $all) {
		$queryBuilder = $this->createQueryBuilder('s');
		$expr = $queryBuilder->expr();

		$queryBuilder
				->where($expr->eq('s.from_user', ':user'))
				->orWhere($expr->eq('s.to_user', ':user'));

		if (!$all) {
			$queryBuilder
					->andWhere($expr->eq('s.status', Share::STATUS_PENDING));
		} else {
			$queryBuilder
					->orderBy('s.status', 'ASC');
		}

		return $queryBuilder->addOrderBy('s.date', 'DESC')
						->setParameter('user', $user)
						->getQuery()
						->getResult();
	}

}
