<?php

namespace Euro\CoinBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Sonata\UserBundle\Model\UserInterface;

/**
 * UserCoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCoinRepository extends EntityRepository {

	public function findBiggestCollections() {
		$queryBuilder = $this->createQueryBuilder('uc');
		$expr = $queryBuilder->expr();

		return $queryBuilder
						->select('uc, u')
						->addSelect('SUM(uc.quantity) AS total')
						->addSelect('COUNT(uc.id) AS total_uniques')
						->join('uc.user', 'u')
						->where($expr->gt('uc.quantity', 0))
						->groupBy('uc.user')
						->having($expr->gt('total', 0))
						->orderBy('total', 'DESC')
						->addOrderBy('total_uniques', 'DESC')
						->setMaxResults(10)
						->getQuery()
						->getResult();
	}

	public function findByCoinsForUser(UserInterface $user, array $coins) {
		$queryBuilder = $this->createQueryBuilder('uc');
		$expr = $queryBuilder->expr();

		return $queryBuilder
						->where($expr->eq('uc.user', ':user'))
						->andWhere($expr->in('uc.coin', ':coins'))
						->setParameters(array(
							'coins' => $coins,
							'user' => $user,
						))
						->getQuery()
						->getResult();
	}

	public function findByUser(UserInterface $user) {
		$queryBuilder = $this->createQueryBuilder('uc');
		$expr = $queryBuilder->expr();

		return $queryBuilder
						->select('uc, c, ct, v, y, w')
						->join('uc.coin', 'c')
						->join('c.country', 'ct')
						->join('c.value', 'v')
						->join('c.year', 'y')
						->leftJoin('y.workshop', 'w')
						->where($expr->eq('uc.user', ':user'))
						->setParameter('user', $user)
						->getQuery()
						->getResult();
	}

	public function findCoinsByUser(UserInterface $user, $type) {
		$queryBuilder = $this->createQueryBuilder('uc');
		$expr = $queryBuilder->expr();

		return $queryBuilder
						->select('uc, c, ct, v, y, w')
						->join('uc.coin', 'c')
						->join('c.country', 'ct')
						->join('c.value', 'v')
						->join('c.year', 'y')
						->leftJoin('y.workshop', 'w')
						->where($expr->eq('uc.user', ':user'))
						->andWhere($expr->eq('c.type', ':type'))
						->andWhere($expr->gt('uc.quantity', 0))
						->orderBy('y.year', 'ASC')
						->addOrderBy('w.short_name', 'ASC')
						->addOrderBy('v.value', 'DESC')
						->setParameters(array(
							'type' => $type,
							'user' => $user,
						))
						->getQuery()
						->getResult();
	}

	public function findDoublesForUser(UserInterface $user) {
		$queryBuilder = $this->createQueryBuilder('uc');
		$expr = $queryBuilder->expr();

		return $queryBuilder
						->select($expr->countDistinct('uc') . ' AS total')
						->addSelect('u.id, u.username, u.email')
						->join('uc.user', 'u')
						->where($expr->neq('uc.user', ':user'))
						->andWhere($expr->gt('uc.quantity - uc.sharing', 1))
						->groupBy('u.id')
						->orderBy('total', 'DESC')
						->addOrderBy('u.username', 'ASC')
						->setParameter('user', $user)
						->getQuery()
						->getResult();
	}

	public function findDoublesFromUser(UserInterface $user) {
		$queryBuilder = $this->createQueryBuilder('uc');
		$expr = $queryBuilder->expr();

		return $queryBuilder
						->select('uc, c, v, y, w')
						->join('uc.coin', 'c')
						->join('c.value', 'v')
						->join('c.year', 'y')
						->leftJoin('y.workshop', 'w')
						->where($expr->eq('uc.user', ':user'))
						->andWhere($expr->gt('uc.quantity - uc.sharing', 1))
						->orderBy('y.year', 'ASC')
						->addOrderBy('w.short_name', 'ASC')
						->addOrderBy('v.value', 'DESC')
						->setParameter('user', $user)
						->getQuery()
						->getResult();
	}

	public function findDoublesFromUserAndCoins(UserInterface $user, array $coins) {
		$queryBuilder = $this->createQueryBuilder('uc');
		$expr = $queryBuilder->expr();

		return $queryBuilder
						->select('uc, c, v, y, w')
						->join('uc.coin', 'c')
						->join('c.value', 'v')
						->join('c.year', 'y')
						->leftJoin('y.workshop', 'w')
						->where($expr->eq('uc.user', ':user'))
						->andWhere($expr->gt('uc.quantity - uc.sharing', 1))
						->andWhere($expr->notIn('c.id', ':coins'))
						->orderBy('y.year', 'ASC')
						->addOrderBy('w.short_name', 'ASC')
						->addOrderBy('v.value', 'DESC')
						->setParameters(array(
							'coins' => $coins,
							'user' => $user,
						))
						->getQuery()
						->getResult();
	}

	public function findMostValuedCollections() {
		$queryBuilder = $this->createQueryBuilder('uc');
		$expr = $queryBuilder->expr();

		return $queryBuilder
						->select('uc, u')
						->addSelect('SUM(uc.quantity * v.value) AS total')
						->addSelect('SUM(v.value) AS total_unique')
						->join('uc.coin', 'c')
						->join('uc.user', 'u')
						->join('c.value', 'v')
						->where($expr->gt('uc.quantity', 0))
						->groupBy('uc.user')
						->having($expr->gt('total', 0))
						->orderBy('total', 'DESC')
						->setMaxResults(10)
						->getQuery()
						->getResult();
	}

}
