<?php

namespace Euro\CoinBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserCoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserCoinRepository extends EntityRepository {

	public function getByUser($user) {
		$queryBuiler = $this->createQueryBuilder('uc');
		$expr = $queryBuiler->expr();

		return $queryBuiler
						->join('uc.coin', 'c')
						->join('c.value', 'v')
						->where($expr->eq('uc.user', ':user'))
						->orderBy('c.year', 'ASC')
						->addOrderBy('v.value', 'DESC')
						->setParameter('user', $user)
						->getQuery()
						->getResult();
	}

	public function getDoublesByUser($user) {
		$queryBuiler = $this->createQueryBuilder('uc');
		$expr = $queryBuiler->expr();

		return $queryBuiler
						->join('uc.coin', 'c')
						->join('c.value', 'v')
						->where($expr->eq('uc.user', ':user'))
						->andWhere($expr->gt('uc.quantity', 1))
						->orderBy('c.year', 'ASC')
						->addOrderBy('v.value', 'DESC')
						->setParameter('user', $user)
						->getQuery()
						->getResult();
	}

}
