<?php

namespace Application\Sonata\NewsBundle\Document;

use Sonata\NewsBundle\Document\BasePostRepository;

/**
 * This file has been generated by the EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   query builder     : http://www.doctrine-project.org/docs/mongodb_odm/1.0/en/reference/query-builder-api.html
 *
 * @author <yourname> <youremail>
 */
class PostRepository extends BasePostRepository {
	
}
