<?php

namespace Application\Sonata\NewsBundle\Document;

use Sonata\NewsBundle\Document\BaseTag;

/**
 * This file has been generated by the EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/docs/mongodb_odm/1.0/en/reference/working-with-objects.html
 *
 * @author <yourname> <youremail>
 */
class Tag extends BaseTag {
	/**
	 * @var integer $id
	 */
	protected $id;

	/**
	 * Get id
	 *
	 * @return integer $id
	 */
	public function getId() {
		return $this->id;
	}

}
