<?php

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser {

	/**
	 * @var integer $id
	 */
	protected $id;

	/**
	 * @var string $country
	 */
	protected $country;

	/**
	 * @var string $show_email
	 */
	protected $show_email = true;

	/**
	 * @var string $coins_sort
	 */
	protected $coins_sort = 'desc';

	/**
	 * @var string $allow_exchanges
	 */
	protected $allow_exchanges = true;

	/**
	 * Get id
	 *
	 * @return integer $id
	 */
	public function getId() {
		return $this->id;
	}

	/**
	 * Set country
	 *
	 * @param string $country
	 * @return User
	 */
	public function setCountry($country) {
		$this->country = $country;

		return $this;
	}

	/**
	 * Get country
	 *
	 * @return string 
	 */
	public function getCountry() {
		return $this->country;
	}

	/**
	 * Set show_email
	 *
	 * @param string $show_email
	 * @return User
	 */
	public function setShowEmail($show_email) {
		$this->show_email = $show_email;

		return $this;
	}

	/**
	 * Get show_email
	 *
	 * @return string 
	 */
	public function getShowEmail() {
		return $this->show_email;
	}

	/**
	 * Set coins_sort
	 *
	 * @param string $coins_sort
	 * @return User
	 */
	public function setCoinsSort($coins_sort) {
		$this->coins_sort = $coins_sort;

		return $this;
	}

	/**
	 * Get coins_sort
	 *
	 * @return string 
	 */
	public function getCoinsSort() {
		return $this->coins_sort;
	}

	/**
	 * Set allow_exchanges
	 *
	 * @param string $allow_exchanges
	 * @return User
	 */
	public function setAllowExchanges($allow_exchanges) {
		$this->allow_exchanges = $allow_exchanges;

		return $this;
	}

	/**
	 * Get allow_exchanges
	 *
	 * @return string 
	 */
	public function getAllowExchanges() {
		return $this->allow_exchanges;
	}

}

