<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( https://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var integer $id
     */
    protected $id;

	/**
	 * @var string $country
	 */
	protected $country;

	/**
	 * @var string $show_email
	 */
	protected $show_email = true;

	/**
	 * @var string $coins_sort
	 */
	protected $coins_sort = 'desc';

	/**
	 * @var string $allow_exchanges
	 */
	protected $allow_exchanges = true;

	/**
	 * @var string $exchange_notification
	 */
	protected $exchange_notification = true;

	/**
	 * @var string $conversation_notification
	 */
	protected $conversation_notification = true;

	/**
	 * @var string $public_profile
	 */
	protected $public_profile = false;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

	/**
	 * Set country
	 *
	 * @param string $country
	 * @return User
	 */
	public function setCountry($country) {
		$this->country = $country;

		return $this;
	}

	/**
	 * Get country
	 *
	 * @return string
	 */
	public function getCountry() {
		return $this->country;
	}

	/**
	 * Set show_email
	 *
	 * @param string $show_email
	 * @return User
	 */
	public function setShowEmail($show_email) {
		$this->show_email = $show_email;

		return $this;
	}

	/**
	 * Get show_email
	 *
	 * @return string
	 */
	public function getShowEmail() {
		return $this->show_email;
	}

	/**
	 * Set coins_sort
	 *
	 * @param string $coins_sort
	 * @return User
	 */
	public function setCoinsSort($coins_sort) {
		$this->coins_sort = $coins_sort;

		return $this;
	}

	/**
	 * Get coins_sort
	 *
	 * @return string
	 */
	public function getCoinsSort() {
		return $this->coins_sort;
	}

	/**
	 * Set allow_exchanges
	 *
	 * @param string $allow_exchanges
	 * @return User
	 */
	public function setAllowExchanges($allow_exchanges) {
		$this->allow_exchanges = $allow_exchanges;

		return $this;
	}

	/**
	 * Get allow_exchanges
	 *
	 * @return string
	 */
	public function getAllowExchanges() {
		return $this->allow_exchanges;
	}

	/**
	 * Set exchange_notification
	 *
	 * @param string $exchange_notification
	 * @return User
	 */
	public function setExchangeNotification($exchange_notification) {
		$this->exchange_notification = $exchange_notification;

		return $this;
	}

	/**
	 * Get exchange_notification
	 *
	 * @return string
	 */
	public function getExchangeNotification() {
		return $this->exchange_notification;
	}

	/**
	 * Set conversation_notification
	 *
	 * @param string $conversation_notification
	 * @return User
	 */
	public function setConversationNotification($conversation_notification) {
		$this->conversation_notification = $conversation_notification;

		return $this;
	}

	/**
	 * Get conversation_notification
	 *
	 * @return string
	 */
	public function getConversationNotification() {
		return $this->conversation_notification;
	}

	/**
	 * Set public_profile
	 *
	 * @param string $public_profile
	 * @return User
	 */
	public function setPublicProfile($public_profile) {
		$this->public_profile = $public_profile;

		return $this;
	}

	/**
	 * Get public_profile
	 *
	 * @return string
	 */
	public function getPublicProfile() {
		return $this->public_profile;
	}
}