<?php

namespace Euro\PrivateMessageBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Sonata\UserBundle\Model\UserInterface;

/**
 * ConversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationRepository extends EntityRepository {

	public function findConversationsForUser(UserInterface $user, $archives) {
		$queryBuilder = $this->createQueryBuilder('c');
		$expr = $queryBuilder->expr();

		return $queryBuilder
						->select('c, m')
						->join('c.from_user', 'fu')
						->join('c.to_user', 'tu')
						->join('c.messages', 'm')
						->where($expr->eq('c.from_user', ':user'))
						->orWhere($expr->eq('c.to_user', ':user'))
						->andWhere($expr->eq('c.open', ':open'))
						->orderBy('m.date', 'DESC')
						->setParameters(array(
							'open' => !$archives,
							'user' => $user,
						))
						->getQuery()
						->getResult();
	}

}
