<?php

namespace Euro\PrivateMessageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository {
	public function findByConversation($id) {
		$queryBuilder = $this->createQueryBuilder('m');
		$expr = $queryBuilder->expr();

		return $queryBuilder
						->select('m, c')
						->join('m.conversation', 'c')
						->where($expr->eq('m.conversation', ':conversation'))
						->orderBy('m.date', 'DESC')
						->setParameter('conversation', $id)
						->getQuery()
						->getResult();
	}
}
