<?php

namespace Euro\PrivateMessageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrivateMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivateMessageRepository extends EntityRepository {

	public function getConversationById($id) {
		$queryBuiler = $this->createQueryBuilder('pm');
		$expr = $queryBuiler->expr();

		return $queryBuiler
						->where($expr->eq('pm.conversation', ':conversation'))
						->orderBy('pm.post_date', 'DESC')
						->setParameter('conversation', $id)
						->getQuery()
						->getResult();
	}

	public function getConversationsByUser($user) {
		$queryBuiler = $this->createQueryBuilder('pm');
		$expr = $queryBuiler->expr();

		return $queryBuiler
						->where($expr->eq('pm.from_user', ':user'))
						->orWhere($expr->eq('pm.to_user', ':user'))
						->orderBy('pm.post_date', 'DESC')
						->setParameter('user', $user)
						->getQuery()
						->getResult();
	}

	public function getNewMessageCount($user) {
		$queryBuiler = $this->createQueryBuilder('pm');
		$expr = $queryBuiler->expr();

		return (int) $queryBuiler
						->select($expr->count('DISTINCT pm.conversation'))
						->where($expr->eq('pm.to_user', ':user'))
						->andWhere($expr->eq('pm.is_read', '0'))
						->setParameter('user', $user)
						->getQuery()
						->getSingleScalarResult();
	}

	public function setConversationRead($conversation, $user) {
		$queryBuiler = $this->createQueryBuilder('pm');
		$expr = $queryBuiler->expr();

		$queryBuiler->update()
				->set('pm.is_read', '1')
				->where($expr->eq('pm.conversation', ':conversation'))
				->andWhere($expr->eq('pm.to_user', ':user'))
				->setParameter('conversation', $conversation)
				->setParameter('user', $user)
				->getQuery()
				->getResult();
	}

}
