show_profile:
    pattern:  /{id}/show
    defaults: { _controller: ApplicationSonataUserBundle:Default:show }
    requirements:
        id: "\d+"

show_user_collection:
    pattern:  /{user_id}/collection/{country_id}/{country_name}
    defaults: { _controller: ApplicationSonataUserBundle:Default:collection, country_id: null, country_name: null }
    requirements:
        country_id: "\d+"
        user_id: "\d+"
