fos_user_profile_show:
    pattern:  /profile
    defaults: { _controller: SonataUserBundle:Profile:show }
    requirements:
        _method: GET

user_edit_preferences:
    pattern: /profile/edit-preferences
    defaults: { _controller: ApplicationSonataUserBundle:Default:preferences }

users_list:
    pattern: /users/list/{page}/{letter}
    defaults: { _controller: ApplicationSonataUserBundle:Default:list, letter: null, page: 1 }
    requirements:
        letter: "[a-zA-Z]|\#"
        page: "\d+"

show_profile:
    pattern:  /profile/{id}/show
    defaults: { _controller: ApplicationSonataUserBundle:Default:show }
    requirements:
        id: "\d+"

show_user_stats:
    pattern:  /profile/{id}/stats
    defaults: { _controller: ApplicationSonataUserBundle:Default:stats }
    requirements:
        id: "\d+"

show_user_collection1:
    pattern:  /profile/{user_id}/collection/{country_id}/{country_name}
    defaults: { _controller: ApplicationSonataUserBundle:Default:collection, country_id: null, country_name: null, type: 1 }
    requirements:
        country_id: "\d+"
        user_id: "\d+"

show_user_collection2:
    pattern:  /profile/{user_id}/collection/commemorative/{country_id}/{country_name}
    defaults: { _controller: ApplicationSonataUserBundle:Default:collection, country_id: null, country_name: null, type: 2 }
    requirements:
        country_id: "\d+"
        user_id: "\d+"

show_user_collection3:
    pattern:  /profile/{user_id}/collection/collector/{country_id}/{country_name}
    defaults: { _controller: ApplicationSonataUserBundle:Default:collection, country_id: null, country_name: null, type: 3 }
    requirements:
        country_id: "\d+"
        user_id: "\d+"

users_query:
    pattern: /users/query
    defaults: { _controller: ApplicationSonataUserBundle:Default:query }
    requirements:
        _method: POST

